#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKDIR="${WORKDIR:-$ROOT_DIR/work}"
ARTIFACT_DIR="$WORKDIR/artifacts"
KERNEL_DIR="$WORKDIR/munch-kernel"
ANYKERNEL_DIR="$WORKDIR/AnyKernel3"
SUSFS_DIR="$WORKDIR/susfs4ksu"
CLANG_PREBUILT_DIR="$WORKDIR/aosp-clang"
KERNEL_REPO="${KERNEL_REPO:-https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git}"
RESUKISU_REPO="${RESUKISU_REPO:-https://github.com/ReSukiSU/ReSukiSU.git}"
SUSFS_REPO="${SUSFS_REPO:-https://gitlab.com/simonpunk/susfs4ksu.git}"
ANYKERNEL_REPO="${ANYKERNEL_REPO:-https://github.com/osm0sis/AnyKernel3.git}"
AOSP_CLANG_REPO="${AOSP_CLANG_REPO:-https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86}"
AOSP_CLANG_REF="${AOSP_CLANG_REF:-android-msm-redbull-4.19-android12-qpr3}"
AOSP_CLANG_VERSION="${AOSP_CLANG_VERSION:-clang-r399163b}"
USE_AOSP_CLANG="${USE_AOSP_CLANG:-0}"
KERNEL_REF="${KERNEL_REF:-munch-s-oss}"
RESUKISU_REF="${RESUKISU_REF:-main}"
SUSFS_REF="${SUSFS_REF:-1.4.2-kernel-4.19}"
ARCH="${ARCH:-arm64}"
DEFCONFIG="${DEFCONFIG:-munch_user_defconfig}"
CROSS_COMPILE="${CROSS_COMPILE:-aarch64-linux-gnu-}"
CROSS_COMPILE_COMPAT="${CROSS_COMPILE_COMPAT:-arm-linux-gnueabi-}"
OBJDUMP="${OBJDUMP:-${CROSS_COMPILE}objdump}"
LLVM_IAS="${LLVM_IAS:-0}"
REAL_CC="${REAL_CC:-clang}"
PYTHON_BIN="${PYTHON_BIN:-python3}"
JOBS="${JOBS:-$(nproc)}"
ZIP_NAME="${ZIP_NAME:-munch-miui14-resukisu.zip}"

mkdir -p "$WORKDIR"
rm -rf "$KERNEL_DIR" "$ANYKERNEL_DIR" "$SUSFS_DIR" "$ARTIFACT_DIR"
mkdir -p "$ARTIFACT_DIR"

if [[ "$USE_AOSP_CLANG" == "1" ]]; then
  rm -rf "$CLANG_PREBUILT_DIR"
  git clone --depth 1 --branch "$AOSP_CLANG_REF" "$AOSP_CLANG_REPO" "$CLANG_PREBUILT_DIR"
  export PATH="$CLANG_PREBUILT_DIR/$AOSP_CLANG_VERSION/bin:$PATH"
fi

git clone --depth 1 --branch "$KERNEL_REF" "$KERNEL_REPO" "$KERNEL_DIR"
git clone --depth 1 --branch "$RESUKISU_REF" "$RESUKISU_REPO" "$KERNEL_DIR/KernelSU"
git clone --depth 1 --branch "$SUSFS_REF" "$SUSFS_REPO" "$SUSFS_DIR"

pushd "$KERNEL_DIR" >/dev/null
bash KernelSU/kernel/setup.sh "$RESUKISU_REF"
git apply "$ROOT_DIR/patches/gcc-wrapper-py3.patch"
git apply "$ROOT_DIR/patches/munch-user-struct-susfs-kabi.patch"
git apply "$ROOT_DIR/patches/aw8697-print-pattern-pointer.patch"
patch -p1 -F3 < "$SUSFS_DIR/kernel_patches/50_add_susfs_in_kernel-4.19.patch"
cp "$SUSFS_DIR/kernel_patches/fs/"* fs/
cp "$SUSFS_DIR/kernel_patches/include/linux/"* include/linux/
python3 "$ROOT_DIR/scripts/apply-munch-resukisu-hooks.py"
popd >/dev/null

make -C "$KERNEL_DIR" O="$WORKDIR/out" ARCH="$ARCH" \
  LLVM=1 LLVM_IAS="$LLVM_IAS" REAL_CC="$REAL_CC" PYTHON="$PYTHON_BIN" \
  OBJDUMP="$OBJDUMP" \
  CROSS_COMPILE="$CROSS_COMPILE" CROSS_COMPILE_COMPAT="$CROSS_COMPILE_COMPAT" \
  "$DEFCONFIG"

"$KERNEL_DIR/scripts/config" --file "$WORKDIR/out/.config" \
  --enable KSU \
  --enable KSU_SUSFS \
  --disable KSU_TRACEPOINT_HOOK \
  --disable KSU_MANUAL_HOOK \
  --disable KPM

make -C "$KERNEL_DIR" O="$WORKDIR/out" ARCH="$ARCH" \
  LLVM=1 LLVM_IAS="$LLVM_IAS" REAL_CC="$REAL_CC" PYTHON="$PYTHON_BIN" \
  OBJDUMP="$OBJDUMP" \
  CROSS_COMPILE="$CROSS_COMPILE" CROSS_COMPILE_COMPAT="$CROSS_COMPILE_COMPAT" \
  olddefconfig

make -C "$KERNEL_DIR" O="$WORKDIR/out" ARCH="$ARCH" \
  LLVM=1 LLVM_IAS="$LLVM_IAS" REAL_CC="$REAL_CC" PYTHON="$PYTHON_BIN" \
  OBJDUMP="$OBJDUMP" \
  CROSS_COMPILE="$CROSS_COMPILE" CROSS_COMPILE_COMPAT="$CROSS_COMPILE_COMPAT" \
  -j"$JOBS" Image

test -s "$WORKDIR/out/arch/$ARCH/boot/Image"
test -s "$WORKDIR/out/System.map"

git clone --depth 1 "$ANYKERNEL_REPO" "$ANYKERNEL_DIR"

source "$ROOT_DIR/packaging/anykernel.env"
cat > "$ANYKERNEL_DIR/anykernel.sh" <<EOF
### AnyKernel3 Ramdisk Mod Script
## autogenerated for Redmi K40S / munch

properties() { '
kernel.string=$KERNEL_STRING
do.devicecheck=$DO_DEVICECHECK
do.modules=$DO_MODULES
do.systemless=$DO_SYSTEMLESS
do.cleanup=$DO_CLEANUP
do.cleanuponabort=$DO_CLEANUPONABORT
device.name1=$DEVICE_NAME_1
device.name2=$DEVICE_NAME_2
device.name3=$DEVICE_NAME_3
supported.versions=$SUPPORTED_VERSIONS
supported.patchlevels=
supported.vendorpatchlevels=
'; }

boot_attributes() {
set_perm_recursive 0 0 755 644 \$RAMDISK/*
set_perm_recursive 0 0 750 750 \$RAMDISK/init* \$RAMDISK/sbin
}

BLOCK=$BLOCK_DEVICE
IS_SLOT_DEVICE=$IS_SLOT_DEVICE
RAMDISK_COMPRESSION=auto
PATCH_VBMETA_FLAG=auto

. tools/ak3-core.sh

dump_boot
write_boot
EOF

cp "$WORKDIR/out/arch/$ARCH/boot/Image" "$ANYKERNEL_DIR/Image"
(cd "$ANYKERNEL_DIR" && zip -r9 "$ARTIFACT_DIR/$ZIP_NAME" . -x '*.git*')
cp "$WORKDIR/out/arch/$ARCH/boot/Image" "$ARTIFACT_DIR/Image"
cp "$WORKDIR/out/.config" "$ARTIFACT_DIR/kernel.config"
cp "$WORKDIR/out/System.map" "$ARTIFACT_DIR/System.map"

cat > "$ARTIFACT_DIR/build-info.txt" <<EOF
kernel_ref=$KERNEL_REF
kernel_sha=$(git -C "$KERNEL_DIR" rev-parse HEAD)
resukisu_ref=$RESUKISU_REF
resukisu_sha=$(git -C "$KERNEL_DIR/KernelSU" rev-parse HEAD)
susfs_ref=$SUSFS_REF
susfs_sha=$(git -C "$SUSFS_DIR" rev-parse HEAD)
use_aosp_clang=$USE_AOSP_CLANG
aosp_clang_ref=$AOSP_CLANG_REF
aosp_clang_version=$AOSP_CLANG_VERSION
objdump=$OBJDUMP
llvm_ias=$LLVM_IAS
zip_name=$ZIP_NAME
EOF

echo "Artifacts are in $ARTIFACT_DIR"
